# Numpy

In [2]:
import numpy as np
k=np.array([1,2,3,5.1])
print(k)

[1.  2.  3.  5.1]


In [232]:
arr = k.astype('float64')
print(arr.dtype)

float64


In [215]:
k=np.array([1,2,3],float)
print(k)

[1. 2. 3.]


In [7]:
k=np.array([1,2,3],float)
print(k.itemsize)
print(k.dtype)

print(k.dtype)

8
float64
float64


In [ ]:
t=np.zeros(6)
print(t)

In [ ]:
t=np.zeros((2,2))
print(t)

In [ ]:
a=np.ones(6)
print(a)

In [210]:
a=np.ones((3,3),int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [211]:
arrayf=np.full((2,3),5)
arrayf

array([[5, 5, 5],
       [5, 5, 5]])

In [4]:
b=np.linspace(6,9,5)
print(b)

[6.   6.75 7.5  8.25 9.  ]


In [3]:
b=np.logspace(6,9,5)
print(b)

[1.00000000e+06 5.62341325e+06 3.16227766e+07 1.77827941e+08
 1.00000000e+09]


In [5]:
c=np.arange(1,20,3)
print(c)

[ 1  4  7 10 13 16 19]


In [ ]:
# create a array with 2 rows and 3 columns
array=np.array([[1,2,3,],[4,5,6]])
array

In [217]:
array.ndim

2

In [ ]:
array1=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
array1.ndim

In [216]:
arraycomplex=np.array([[1,2,3],[4,5,6]],complex)
arraycomplex

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [218]:
array2=np.empty([2,3])
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [219]:
arrayr=np.random.random((4,4))
arrayr

array([[0.79032835, 0.07402793, 0.87899804, 0.97623583],
       [0.46912498, 0.7013187 , 0.89499326, 0.41838621],
       [0.26430849, 0.4598793 , 0.85873271, 0.27488878],
       [0.19364074, 0.58152022, 0.59976914, 0.84105917]])

In [60]:
arrayr=np.random.randint(1,100,10)
arrayr

array([61, 83, 38,  4, 86,  2, 85, 80, 49, 74])

In [242]:
arrayr=np.random.randint(1,4,10)
arrayr

array([3, 2, 3, 3, 3, 2, 1, 1, 2, 1])

In [220]:
## identity matrix


arrayi=np.eye((3))
arrayi

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [221]:
## identity function
arrayid=np.identity(5);arrayid


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
array=np.array([[[2,1,3,4],[2,1,5,6]],[[12,11,13,14],[22,21,25,26]],[[42,41,43,44],[72,71,75,76]]])
array

In [222]:
array.shape
#3 subarray
#2 row
# 4 colum

(8, 8)

In [244]:
array.reshape(2,4,3)

ValueError: cannot reshape array of size 64 into shape (2,4,3)

In [224]:
array.ndim

2

In [ ]:

print("itemsize:",array.itemsize)


In [ ]:
print("data type:",array.dtype)


In [ ]:
print("data type:",array.size)


### Array operations

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,22],[33,44]])

#adding
print(a+b)
print(np.add(a,b))

In [ ]:
# subtract
print(b-a)
print(np.subtract(b,a))


In [ ]:
#multiply

print(a*b)
print(np.multiply(a,b))

In [ ]:
# didvide
print(a/b)
print(np.divide(a,b))

In [ ]:
# modulo
print(a%b)
#print(np.modulo(a,b))

In [ ]:
# raise every elemnt to power of 2
print(a**2)
#print(np.power(b,a))

In [ ]:
#add 2 to evry element
print(a+2)

In [ ]:
# raise every elemnt to power of 3
print(a**3)

In [ ]:
#a+=b is same as a=a+b
a+=b
print(a)

In [ ]:
#other operations exp(),sqrt()
print(np.sqrt(a))
print(np.power(a,2))

### statistical operations

In [226]:
a=np.array([[1,2,3],[4,5,6]])
np.sum(a)

21

In [ ]:
print(a.min())
print(a.max())
print(a.max(axis=0))
print(a.max(axis=1))
print(a.cumsum(axis=0))

In [ ]:
print(np.mean(a))
print(np.median(a))
print(np.corrcoef(a))# how each elelment is changing with respective ro other
print(np.std(a1))
print(np.count_nonzero(a==2))

In [3]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[11,22,33],[33,44,55],[33,44,66]])
a@b

array([[176, 242, 341],
       [330, 462, 649]])

In [ ]:
print(np.matmul(a,b))

### transpose


In [227]:
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np
# trace matrix
print(np.trace(a))

5


In [229]:
# inverse matrix
a=np.array([[1,2],[3,4]])
b=np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Bitwise OPerations

In [13]:
a=np.array([[1,2,3,4],[6,7,8,9]])
b=np.array([[11,23,43,44],[66,79,88,97]])
print(np.bitwise_and(a,b))

[[1 2 3 4]
 [2 7 8 1]]


In [14]:
print(np.invert(a))

[[ -2  -3  -4  -5]
 [ -7  -8  -9 -10]]


### Copying and sorting

In [14]:
a=np.array([[1,2,3],[4,5,6]])
b=a
print(b)# no copy

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b is a)

In [ ]:
#shallow copy it will effect the main array
shaa=a.view()
print(shaa)

In [ ]:
shaa+=1
print(shaa)
print(a)

In [7]:
#deep copy it will not effect the main array
deep=a.copy()
deep+=2
print(deep)
print(a)

[[ 3  4  5  6]
 [ 8  9 10 11]]
[[1 2 3 4]
 [6 7 8 9]]


In [230]:
a.sort();a


array([[1, 2],
       [3, 4]])

In [15]:
#colum sorting
a.sort(axis=0);b

array([[1, 2, 3],
       [4, 5, 6]])

### Comparison

In [18]:
ba=np.array([[3,3,7],[1,5,2]])

In [19]:
print(ba>5)

[[False False  True]
 [False False False]]


In [22]:
print(a<b)

[[False False False]
 [False False False]]


In [27]:
print(np.array_equal(a,b))


True


### Indexing and slicing

In [29]:
arr=np.array([1,2,3,4,556])
arr[2:6]

array([  3,   4, 556])

In [33]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1[:2,1:3]

array([[2, 3],
       [5, 6]])

In [38]:
print(arr1.ravel())

[1 2 3 4 5 6]


In [34]:
print(arr1.flatten())


[1 2 3 4 5 6]


In [36]:
np.append(arr,arr1)

array([  1,   2,   3,   4, 556,   1,   2,   3,   4,   5,   6])

### Splitting and stacking

In [237]:
data=np.arange(24)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
d1=data.reshape(6,4)

In [43]:
#split horizontal
data1=np.vsplit(d1,2);data1

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [50]:
data2=np.hsplit(d1,2);data2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [45]:
# extracting the first split of data2
data2[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]])

In [53]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,4,3],[4,5,6]])
k=np.vstack((arr1,arr2))
k


array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 3],
       [4, 5, 6]])

In [54]:
k=np.hstack((arr1,arr2))
k

array([[1, 2, 3, 1, 4, 3],
       [4, 5, 6, 4, 5, 6]])

In [56]:
arr=np.array([1,2,3,4,556])
ad1=np.delete(arr,2)
ad1

array([  1,   2,   4, 556])

In [59]:
arr=np.array([[1,2,3],[3,4,556]])

ad1=np.delete(arr,2,axis=1)
ad1

array([[1, 2],
       [3, 4]])

### Exercise

In [67]:
import numpy as np


arr = np.array([
    
    [
        [1, 2, 3], 
        [4, 5, 6]
    ],
    [
        [7, 8, 9], 
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ],
    [
        [19, 20, 21], 
        [22, 23, 24]
    ]
])
max0 = np.max(arr, axis=0)
max1 = np.max(arr, axis=1)
max2 = np.max(arr, axis=2)
print("Max  axis 0:", max0)
print("Max  axis 1:", max1)
print("Max  axis 2:", max2)


Maximum along axis 0: [[19 20 21]
 [22 23 24]]
Maximum along axis 1: [[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]
Maximum along axis 2: [[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]]


In [16]:
array1 = np.full(10,5)
print(array1)
#b
print(array1.itemsize)
print(array1.size*array1.itemsize)

#c
array2=np.arange(0,91,10)
print(array2.size)
#d
print(np.flip(array2))
#e
print(array1+array2)



[5 5 5 5 5 5 5 5 5 5]
4
40
10
[90 80 70 60 50 40 30 20 10  0]
[ 5 15 25 35 45 55 65 75 85 95]


In [31]:
np.sort(array2)[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

In [201]:
array=np.zeros((8, 8), dtype=int)
k=1
temp=0
for i in array:
    temp=temp+1
    count=0
    for j in i:
        if(temp%2==0):
            if(count%2==0):
                print(j,end='')
                count=count+1
            else:
                count=count+1
                print(k,end='')
        else:
            if(count%2==0):
                count=count+1
                print(k,end='')
            else:
                print(j,end='')
                count=count+1
            
    print()
        
#print(array)

10101010
01010101
10101010
01010101
10101010
01010101
10101010
01010101


In [7]:
array=np.zeros((8, 8), dtype=int)
array[::2, ::2]=1
array[1::2,1::2]=1
print(array)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [8]:
import numpy as np
dsid = np.arange(1, 201)
deid = np.arange(201, 401)
daid = np.arange(401, 601)



In [9]:
dssalaries = np.random.randint(20000, 50001,200)
desalaries = dssalaries * 1.5
dasalaries = dssalaries + 2000
#print(dssalaries)
# print(desalaries)
# print(dasalaries)

In [10]:
dsctc = np.sum(dssalaries)
dectc = np.sum(desalaries)
dactc = np.sum(dasalaries)

In [11]:
allsalaries = np.concatenate((dssalaries, desalaries, dasalaries))
top10salaries = np.sort(allsalaries)[-10:-1]
print(top10salaries)

[71800.5 71802.  72408.  72745.5 72976.5 73044.  73125.  73369.5 73788. ]


In [130]:
topdssalaries=np.sum(np.sort(dssalaries)[-10:])
topdesalaries=np.sum(np.sort(desalaries)[-10:])
topdasalaries=np.sum(np.sort(dasalaries)[-10:])
print(topdssalaries)
print(topdesalaries)
print(topdasalaries)

489260
733890.0
509260


In [136]:
top10count = np.count_nonzero(allsalaries >= np.sort(allsalaries)[-10])
print(top10count)

10


In [137]:
highsalarycount = np.count_nonzero(allsalaries > 40000)
print(highsalarycount)

281


In [183]:
# need to check
#dssalaries[dssalaries < 35000] *= 1.2
# dssalaries = dssalaries.astype(float) 
# dssalaries[dssalaries < 35000] *= 1.2
# dssalaries = dssalaries.astype(int)
# print(dssalaries)

check = dssalaries < 35000
dssalaries[check] = (dssalaries[check] * 1.2)

print(dssalaries)


[43147 36097 35283 46893 43630 27592 30963 39620 48703 37251 45093 39340
 38077 25458 36049 39092 40412 40149 43623 29428 33820 28372 36664 29818
 35980 37064 46658 36780 39155 41138 37446 48625 45388 41263 35557 38725
 49115 43442 39632 40568 48812 26515 41322 39535 30679 27104 40691 25402
 32598 49723 36908 35604 46116 29982 45130 46297 36665 35859 42495 37054
 47860 36681 34702 39013 49985 41439 28130 40084 30349 27151 32472 39023
 36096 30348 38251 39188 45826 40594 49385 41847 26529 37990 45214 40254
 35428 48703 44797 40918 39495 41776 28258 26715 39021 31252 33330 32089
 35415 42680 36618 39228 46044 38424 45554 39252 26167 47572 41413 32084
 42308 48462 36555 44460 49453 47256 44315 37537 28342 46205 41634 39139
 26524 40508 38029 42123 38990 31021 26644 24544 46957 35087 35906 36824
 29475 35020 40857 41162 29161 27956 48024 48980 24261 43639 34111 25495
 48771 24432 37225 34782 34080 45242 28135 34843 44608 36064 29266 45587
 41148 47530 47650 37711 31598 34245 39495 35247 43

In [243]:
deleteindices = np.where(deid > 380)
deid = np.delete(deid, deleteindices)
desalaries = np.delete(desalaries, deleteindices)
print(deleteindices)
print(deid)


# deid = np.delete(deid, np.where(deid > 380))
# desalaries = np.delete(desalaries, np.where(deid > 380))
# print(np.count_nonzero(desalaries))


(array([180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194], dtype=int64),)
[201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254
 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290
 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308
 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326
 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344
 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362
 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380]


In [191]:
newid = np.arange(701, 706)
deid = np.concatenate((deid, newid))
desalaries = np.concatenate((desalaries, np.random.randint(20000, 50001,5)))
print(desalaries)


[64720.5 45121.5 52924.5 70339.5 65445.  34491.  38704.5 59430.  73054.5
 55876.5 67639.5 59010.  57115.5 31822.5 54073.5 58638.  50515.5 60223.5
 65434.5 36786.  42276.  35466.  54996.  37273.5 53970.  55596.  69987.
 55170.  58732.5 51423.  46807.5 72937.5 68082.  51579.  44446.5 58087.5
 73672.5 65163.  49540.5 60852.  73218.  33144.  61983.  49419.  38349.
 33880.5 61036.5 31753.5 40747.5 74584.5 46135.5 53406.  69174.  37477.5
 67695.  69445.5 54997.5 44824.5 63742.5 55581.  71790.  55021.5 43378.5
 48766.5 74977.5 51799.5 35163.  50106.  37936.5 33939.  40590.  58534.5
 54144.  37935.  47814.  58782.  68739.  60891.  74077.5 52309.5 33162.
 47488.5 67821.  60381.  53142.  73054.5 67195.5 61377.  49369.5 52221.
 35323.5 33394.5 48777.  39066.  41662.5 40111.5 53122.5 64020.  45772.5
 49035.  69066.  57636.  68331.  58878.  32709.  71358.  51766.5 40105.5
 63462.  72693.  54832.5 66690.  74179.5 70884.  66472.5 56305.5 35428.5
 69307.5 52042.5 48924.  33156.  50635.5 47536.5 63184.